apiVersion: v1
kind: ConfigMap
metadata:
  name: azbankgateways-config
  labels:
    app: azbankgateways-test
data:
  # تنظیمات Django
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  TIME_ZONE: "Asia/Tehran"
  LANGUAGE_CODE: "fa"
