apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default  # یا namespace مورد نظر خود

resources:
  - secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: azbankgateways-test
  managed-by: kustomize
